/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "#F5F3EF",
        card: "#FFFFFF",
        ink: "#15171A",
        body: "#5B5D62",
        muted: "#94969B",
        hairline: "#E7E4DE",
        "hairline-strong": "#D8D4CC",
        graphite: "#0E2A4D",
        "graphite-soft": "#173A63",
        "graphite-text": "#8A9BB5",
        "graphite-text-strong": "#F0F3F8",
        "member-card-bg": "#081A33",
        accent: "#F5760F",
        "accent-soft": "#FDEEE0",
        "accent-hover": "#D4640D",
        "on-accent": "#FDFCFA",
        success: "#3F6B4A",
        "success-soft": "#EBF2EC",
        warning: "#9A6B1F",
        "warning-soft": "#FBF1DF",
        danger: "#9B3A34",
        "danger-soft": "#FAECEA",
        info: "#3F5E70",
        "info-soft": "#E8EEF0",
      },
      fontFamily: {
        display: ["var(--font-archivo)", "Archivo", "sans-serif"],
        bebas: ["var(--font-bebas-neue)", "Bebas Neue", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "12px",
      },
      fontSize: {
        'display-2xl': ['clamp(48px, 8.5vw, 96px)', { lineHeight: '1.0', letterSpacing: '0px' }],
        'display-xl': ['clamp(32px, 5.5vw, 56px)', { lineHeight: '1.05', letterSpacing: '-0.5px' }],
        'display-lg': ['clamp(22px, 3.8vw, 38px)', { lineHeight: '1.1', letterSpacing: '-0.3px' }],
        'display-md': ['clamp(20px, 2vw + 8px, 28px)', { lineHeight: '1.15', letterSpacing: '-0.2px' }],
        'display-sm': ['clamp(18px, 1vw + 12px, 22px)', { lineHeight: '1.2', letterSpacing: '0' }],
        'stat-number': ['clamp(20px, 1.5vw + 11px, 26px)', { lineHeight: '1.0', letterSpacing: '0' }],
        'title-lg': ['17px', { lineHeight: '1.3', letterSpacing: '0' }],
        'title-md': ['14.5px', { lineHeight: '1.4', letterSpacing: '0' }],
        'label-uppercase': ['10.5px', { lineHeight: '1.3', letterSpacing: '0.8px' }],
        'body-md': ['13.5px', { lineHeight: '1.5', letterSpacing: '0' }],
        'body-sm': ['12.5px', { lineHeight: '1.5', letterSpacing: '0' }],
        'caption': ['11.5px', { lineHeight: '1.4', letterSpacing: '0.15px' }],
        'button': ['13.5px', { lineHeight: '1.0', letterSpacing: '0.1px' }],
        'nav-link': ['13.5px', { lineHeight: '1.4', letterSpacing: '0' }],
      },
    },
  },
  plugins: [],
};
